---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: search
spec:
  template:
    spec:
      containers:
        - name: search
          image: shokohsc/search
          env:
            - name: ENV
              value: development
            - name: USE_SENTRY
              value: "true"
            - name: SENTRY_DSN
              value: https://2f15ffed2e254ced911e78de9312afe0\@glitchtip.shokohsc.home/1
            - name: API_URL
              value: dev.sidekick.shokohsc.home
          resources:
            requests:
              cpu: 10m
              memory: 64M
            limits:
              cpu: 1000m
              memory: 256M
